# Generated by Django 3.0.8 on 2020-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_carditem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
