# Generated by Django 3.0.8 on 2020-08-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20200831_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
    ]
